### PR TITLE
Fix typo in log message

### PR DESCRIPTION
**Pull request by wdecoster**

### CODE REVIEW

**Comment by fritzsedlazeck** [comment]
haha thanks for fixing our typos :). 
@philres its on you to accept.

**Comment by philres** [comment]
Hehe thx! I guess spelling has never been our strong suit. :)

**Comment by fritzsedlazeck** [comment]
yeah @wdecoster also fixed my typos in SURVIVOR :)

**Comment by wdecoster** [comment]
That's a quite easy way to contribute a tiny bit to your great projects!

**Pull request merged**
